apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::982933382226:user/colleague-user
      username: colleague-user
      groups:
        - system:viewers
