pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build & Run with Docker Compose') {
            steps {
                sh '''
                  cd ..
                  docker-compose down || true
                  docker-compose up -d --build
                '''
            }
        }
    }
}
