pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  cd backend
                  docker build -t flask-backend .
                '''
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                  docker rm -f flask-backend || true
                '''
            }
        }

        stage('Run New Container') {
            steps {
                sh '''
                  docker run -d \
                    --name flask-backend \
                    -p 5000:5000 \
                    flask-backend
                '''
            }
        }
    }
}
