pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build & Run with Docker Compose') {
            steps {
                sh '''
                  /usr/bin/docker-compose -f ../docker-compose.yml down || true
                  /usr/bin/docker-compose -f ../docker-compose.yml up -d --build


                '''
            }
        }
    }
}
