pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                sh '''
                  cd infra
                  terraform init
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                  cd infra
                  terraform plan
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                  cd infra
                  terraform apply -auto-approve
                '''
            }
        }
    }
}
